"""Tests for the Truflation→BLS bridge Forecaster."""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from thales.evaluation.harness import Forecast, walk_forward
from thales.models.baselines import PersistenceBaseline
from thales.models.composition.bridge import TruflationToBLSBridge


def _make_panel(T: int = 120, alpha: float = 0.5, beta: float = 0.95,
                  noise_sd: float = 0.05, seed: int = 0) -> pd.DataFrame:
    """Panel with truf_yoy AR(1) + bls_yoy = alpha + beta*truf + noise."""
    rng = np.random.default_rng(seed)
    idx = pd.date_range("2018-01-31", periods=T, freq="ME")
    truf = np.empty(T)
    truf[0] = 2.0
    for t in range(1, T):
        truf[t] = 0.95 * truf[t - 1] + rng.normal(0, 0.1)
    bls = alpha + beta * truf + rng.normal(0, noise_sd, size=T)
    return pd.DataFrame({"truf_yoy": truf, "bls_yoy": bls}, index=idx)


# ─── Bridge basic API ─────────────────────────────────────────────────────


def test_bridge_recovers_alpha_beta():
    """When the panel was generated by a clean linear bridge, the bridge
    should recover alpha and beta within tight tolerance."""
    panel = _make_panel(T=120, alpha=0.5, beta=0.95, noise_sd=0.05)
    inner = PersistenceBaseline(target_col="truf_yoy")
    bridge = TruflationToBLSBridge(
        inner=inner, target_truf_col="truf_yoy", target_bls_col="bls_yoy",
        bridge_window_months=60,
    )
    origin = panel.index[60]
    target = panel.index[61]
    fc = bridge.fit_predict(panel.loc[: origin], origin, target)
    a = fc.metadata["bridge_alpha"]
    b = fc.metadata["bridge_beta"]
    assert abs(a - 0.5) < 0.10, f"alpha {a:.4f} vs 0.5"
    assert abs(b - 0.95) < 0.05, f"beta {b:.4f} vs 0.95"


def test_bridge_produces_bls_forecast():
    panel = _make_panel(T=80)
    inner = PersistenceBaseline(target_col="truf_yoy")
    bridge = TruflationToBLSBridge(
        inner=inner, target_truf_col="truf_yoy", target_bls_col="bls_yoy",
    )
    origin = panel.index[40]
    target = panel.index[41]
    fc = bridge.fit_predict(panel.loc[: origin], origin, target)
    expected_point = (fc.metadata["bridge_alpha"]
                         + fc.metadata["bridge_beta"]
                         * panel.loc[origin, "truf_yoy"])
    assert abs(fc.point - expected_point) < 1e-9


def test_bridge_widens_bands_with_residual_variance():
    """If inner has bands, bridged bands should be wider by the bridge
    residual SD (since the bridge introduces additional noise)."""
    panel = _make_panel(T=80, noise_sd=0.20)  # noisy bridge
    inner = PersistenceBaseline(target_col="truf_yoy")
    bridge = TruflationToBLSBridge(
        inner=inner, target_truf_col="truf_yoy", target_bls_col="bls_yoy",
    )
    origin = panel.index[40]
    target = panel.index[41]
    fc = bridge.fit_predict(panel.loc[: origin], origin, target)

    inner_fc = inner.fit_predict(panel.loc[: origin], origin, target)
    inner_width = inner_fc.hi80 - inner_fc.lo80 if inner_fc.has_bands else 0
    bridged_width = fc.hi80 - fc.lo80
    assert bridged_width > inner_width * abs(fc.metadata["bridge_beta"]), (
        f"bridged width {bridged_width:.4f} should be wider than scaled inner "
        f"width {inner_width * abs(fc.metadata['bridge_beta']):.4f}")


def test_bridge_handles_negative_beta():
    """If true beta is negative (anti-cointegration), bridge should
    still work and produce sensible bands (lo < hi)."""
    panel = _make_panel(T=80, alpha=0.5, beta=-0.8, noise_sd=0.05)
    inner = PersistenceBaseline(target_col="truf_yoy")
    bridge = TruflationToBLSBridge(
        inner=inner, target_truf_col="truf_yoy", target_bls_col="bls_yoy",
    )
    origin = panel.index[40]
    target = panel.index[41]
    fc = bridge.fit_predict(panel.loc[: origin], origin, target)
    assert fc.lo80 < fc.hi80
    assert fc.lo95 < fc.hi95
    assert fc.metadata["bridge_beta"] < 0


def test_bridge_through_harness():
    """Bridge should walk through walk_forward → score without errors."""
    panel = _make_panel(T=80)
    inner = PersistenceBaseline(target_col="truf_yoy")
    bridge = TruflationToBLSBridge(
        inner=inner, target_truf_col="truf_yoy", target_bls_col="bls_yoy",
        model_id="test_bridge",
    )
    origins = panel.index[30:75]
    forecasts = walk_forward(bridge, panel, "bls_yoy", origins, horizon=1)
    assert len(forecasts) > 30


def test_bridge_metadata_carries_inner_metadata():
    panel = _make_panel(T=80)
    inner = PersistenceBaseline(target_col="truf_yoy")
    bridge = TruflationToBLSBridge(
        inner=inner, target_truf_col="truf_yoy", target_bls_col="bls_yoy",
    )
    origin = panel.index[40]
    target = panel.index[41]
    fc = bridge.fit_predict(panel.loc[: origin], origin, target)
    # inner metadata includes 'baseline': 'persistence'
    assert fc.metadata["baseline"] == "persistence"
    # bridge metadata
    assert "bridge_alpha" in fc.metadata
    assert "bridge_beta" in fc.metadata
    assert "bridge_residual_sd" in fc.metadata


def test_bridge_short_paired_window_raises():
    """If inner+outer pairs have <6 joint observations the bridge should raise."""
    # Build a panel where bls_yoy is mostly NaN
    panel = _make_panel(T=80)
    panel = panel.copy()
    # Null out all but 4 rows of BLS
    panel.loc[panel.index[5:], "bls_yoy"] = np.nan

    inner = PersistenceBaseline(target_col="truf_yoy")
    bridge = TruflationToBLSBridge(
        inner=inner, target_truf_col="truf_yoy", target_bls_col="bls_yoy",
    )
    origin = panel.index[60]
    target = panel.index[61]
    with pytest.raises(ValueError, match="≥6"):
        bridge.fit_predict(panel.loc[: origin], origin, target)
