"""Recovery tests for the TVP-Commodity archetype model.

Phase 1.1 gate-1 evidence: the Kalman/RTS-smoother estimator recovers
the true latent ``β_t`` path generated by the synthetic DGP.

Three increasingly-strict checks:

  1. **Mean recovery** — time-average smoothed β within 0.05 of the
     time-average true β. This is the easy bar; static OLS already passes
     this when β drift is small.
  2. **Path recovery** — Pearson(smoothed β, true β) > 0.7 across the
     whole sample. This is the actual TVP win — picks up the drift, not
     just the average.
  3. **MAE recovery** — mean absolute error |smoothed β − true β| < 0.07
     averaged over time. Quantitative metric to track regressions.

Plus hyperparameter recovery sanity checks (σ_ε, σ_β within 50% of
truth).
"""

from __future__ import annotations

import numpy as np
import pytest

from thales.models.archetypes.commodity import fit_tvp_commodity
from thales.synthetic.commodity_passthrough import (
    simulate_commodity_passthrough,
    static_ols_recovery,
)


# ─── Mean recovery ────────────────────────────────────────────────────────


def test_mean_beta_recovery():
    """Time-average smoothed β within 0.05 of time-average true β.

    Uses a low-SV regime (sv_log_mean=-7.0, sv_shock_sd=0.05) so the
    constant-σ_ε model assumption isn't catastrophically violated.
    """
    dgp = simulate_commodity_passthrough(
        T=2000, beta_0=0.35, beta_drift_sd=0.005,
        commodity_shock_sd=0.02,
        sv_log_mean=-7.0, sv_shock_sd=0.05, sv_persistence=0.99,
        seed=0,
    )
    fit = fit_tvp_commodity(dgp.commodity, dgp.retail, beta_0=0.5)
    assert abs(fit.beta_smoothed.mean() - dgp.true_beta.mean()) < 0.05, (
        f"mean β: smoothed={fit.beta_smoothed.mean():.4f}, "
        f"true={dgp.true_beta.mean():.4f}"
    )


# ─── Path recovery ────────────────────────────────────────────────────────


def test_path_recovery_correlation():
    """Smoothed β path tracks the true β path — Pearson > 0.7."""
    dgp = simulate_commodity_passthrough(
        T=2000, beta_0=0.35, beta_drift_sd=0.008,
        commodity_shock_sd=0.02, sv_log_mean=-6.0,
        seed=42,
    )
    fit = fit_tvp_commodity(dgp.commodity, dgp.retail, beta_0=0.5)
    # Drop burn-in (first 100 obs — initial filter uncertainty dominates)
    burn = 100
    r = np.corrcoef(fit.beta_smoothed[burn:], dgp.true_beta[burn:])[0, 1]
    assert r > 0.7, f"path correlation {r:.3f} below 0.7 threshold"


def test_path_recovery_mae():
    """Mean absolute error on smoothed β path < 0.07."""
    dgp = simulate_commodity_passthrough(
        T=2000, beta_0=0.35, beta_drift_sd=0.008,
        commodity_shock_sd=0.02, sv_log_mean=-6.0,
        seed=7,
    )
    fit = fit_tvp_commodity(dgp.commodity, dgp.retail, beta_0=0.5)
    burn = 100
    mae = np.mean(np.abs(fit.beta_smoothed[burn:] - dgp.true_beta[burn:]))
    assert mae < 0.07, f"path MAE {mae:.4f} above 0.07 threshold"


# ─── Comparison vs static OLS ─────────────────────────────────────────────


def test_tvp_beats_static_ols_on_path_correlation():
    """The whole point of the TVP model: it should track the drifting β
    better than static OLS, which collapses to a single estimate."""
    dgp = simulate_commodity_passthrough(
        T=3000, beta_0=0.35, beta_drift_sd=0.01,
        commodity_shock_sd=0.02, sv_log_mean=-6.0,
        seed=11,
    )
    fit = fit_tvp_commodity(dgp.commodity, dgp.retail, beta_0=0.5)
    _, ols_beta, _ = static_ols_recovery(dgp)

    burn = 100
    tvp_mae = np.mean(np.abs(fit.beta_smoothed[burn:] - dgp.true_beta[burn:]))
    ols_mae = np.mean(np.abs(ols_beta - dgp.true_beta[burn:]))

    assert tvp_mae < ols_mae, (
        f"TVP MAE {tvp_mae:.4f} should be < static OLS MAE {ols_mae:.4f}"
    )


# ─── Hyperparameter recovery ──────────────────────────────────────────────


def test_sigma_eps_recovery_when_no_sv():
    """When SV is essentially constant (sv_log_mean = -10, very small noise),
    σ_ε should recover the true noise SD within 50%.

    Loose tolerance because (a) σ_ε is correlated with σ_β in likelihood
    and (b) we're not modeling SV — any SV in the DGP shows up as extra
    apparent ε noise.
    """
    true_log_sigma = -8.0  # → exp(-4) ≈ 0.0183 per-step SD
    dgp = simulate_commodity_passthrough(
        T=2000, beta_0=0.35, beta_drift_sd=0.001,
        sv_log_mean=true_log_sigma, sv_shock_sd=0.05,
        sv_persistence=0.99,
        seed=3,
    )
    fit = fit_tvp_commodity(dgp.commodity, dgp.retail, beta_0=0.5)
    expected_sigma = np.exp(true_log_sigma / 2.0)
    ratio = fit.sigma_eps / expected_sigma
    assert 0.5 < ratio < 2.0, (
        f"σ_ε estimate {fit.sigma_eps:.5f} vs expected {expected_sigma:.5f} "
        f"(ratio {ratio:.2f})"
    )


def test_sigma_beta_recovery_order_of_magnitude():
    """σ_β should be on the same order of magnitude as the true drift SD."""
    true_drift = 0.005
    dgp = simulate_commodity_passthrough(
        T=2000, beta_0=0.35, beta_drift_sd=true_drift,
        sv_log_mean=-7.0,  # low noise so σ_β is identifiable
        seed=2,
    )
    fit = fit_tvp_commodity(dgp.commodity, dgp.retail, beta_0=0.5)
    ratio = fit.sigma_beta / true_drift
    assert 0.3 < ratio < 3.0, (
        f"σ_β estimate {fit.sigma_beta:.5f} vs true {true_drift:.5f} "
        f"(ratio {ratio:.2f})"
    )


# ─── Determinism ──────────────────────────────────────────────────────────


def test_fit_is_deterministic_for_same_data():
    dgp = simulate_commodity_passthrough(T=1000, seed=99)
    fit_a = fit_tvp_commodity(dgp.commodity, dgp.retail)
    fit_b = fit_tvp_commodity(dgp.commodity, dgp.retail)
    np.testing.assert_allclose(fit_a.beta_smoothed, fit_b.beta_smoothed,
                                  rtol=1e-6)
    assert fit_a.alpha == pytest.approx(fit_b.alpha)


# ─── Smoke-edge cases ─────────────────────────────────────────────────────


def test_fit_rejects_short_series():
    dgp = simulate_commodity_passthrough(T=30, seed=0)
    with pytest.raises(ValueError, match="≥50"):
        fit_tvp_commodity(dgp.commodity, dgp.retail)


def test_fit_rejects_mismatched_inputs():
    with pytest.raises(ValueError, match="same length"):
        fit_tvp_commodity(np.zeros(100), np.zeros(50))
